[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
primaryColor = "#0ea5e9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#F4F4F5"
textColor = "#09090B"
font = "sans serif"
